#!/bin/bash

echo "🚀 Generador de Landing de Destinos (DESARROLLO)"
echo "================================================"
echo ""
echo "Generando todas las secciones..."
echo ""

node build-destinos-dev.mjs && \
node build-quoter.mjs && \
node build-destinos-part2.mjs && \
node build-destinos-final-dev.mjs

echo ""
echo "✅ ¡Listo! Revisa el archivo: a365/destinos-dev.html"
echo ""
echo "Estructura generada:"
echo "1. Hero - Requisitos para viajar a Brasil en 2025"
echo "2. Cotizador (Single-SPA) con bg-bg-alt-secondary"
echo "3. ImageText - ¿Qué necesito para viajar?"
echo "4. ImageText - ¿Es obligatorio el seguro?"
echo "5. SectionCards - ¿Qué debe incluir tu seguro? (8 coberturas)"
echo "6. SectionPlans - Nuestros planes (4 planes)"
echo "7. SectionRequirements - Requisitos para viajar (Grid 2x2)"
echo "8. FAQs - Preguntas frecuentes"
echo "9. Blog - Últimas guías"
echo "10. PreFooter - CTA final"
echo ""
echo "📦 Assets locales (localhost):"
echo "   - Quoter: localhost:5006/a365-quoter.js"
echo "   - API: localhost:5001/a365-api.js"
echo "   - Core: localhost:5003/a365-core.js"
echo "   - DSys: localhost:5057/a365-dsys.js"
echo "   - Blog API: localhost:3001/ar/wp-json/wp/v2/posts"
echo ""
echo "Para probar localmente:"
echo "   cd /home/impurerose/dev/directus/a365"
echo "   python3 -m http.server 8080"
echo "   Abrir: http://localhost:8080/destinos-dev.html"
echo ""
echo "⚠️  Asegúrate de que todos los servidores locales estén corriendo:"
echo "   - Quoter: npm run dev en /quoter"
echo "   - API: npm run dev en /api"
echo "   - Core: npm run dev en /core"
echo "   - DSys: npm run dev en /dsys"
