#!/bin/bash

echo "🚀 Generador Automático de HTML Estático"
echo "=========================================="
echo ""
echo "📋 INSTRUCCIONES SIMPLES:"
echo ""
echo "Opción A - Automático (Recomendado):"
echo "  1. Abre otra terminal"
echo "  2. Ejecuta: npm run dev"
echo "  3. Abre http://localhost:5174 en Chrome/Firefox"
echo "  4. Presiona F12 (DevTools)"
echo "  5. En la consola, pega y ejecuta:"
echo ""
echo "     copy(document.querySelector('#root').outerHTML)"
echo ""
echo "  6. Abre: dist/mexico.html en tu editor"
echo "  7. Busca el comentario: <!-- PASO 1: COPIAR HTML AQUÍ -->"
echo "  8. Pega (Ctrl+V) el HTML copiado"
echo "  9. Guarda el archivo"
echo "  10. ¡Listo para Directus!"
echo ""
echo "Opción B - Manual rapido:"
echo "  1. npm run dev (en otra terminal)"
echo "  2. Abre http://localhost:5174"
echo "  3. Click derecho → 'Ver código fuente de la página'"
echo "  4. Busca <div id=\"root\">  y copia todo hasta </div>"
echo "  5. Pega en dist/mexico.html"
echo ""
echo "=========================================="
echo ""
echo "💡 Tips:"
echo "  - El archivo dist/mexico.html ya tiene todo el setup (CDNs, scripts)"
echo "  - Solo necesitas el HTML renderizado del navegador"
echo "  - Los accordions funcionarán automáticamente"
echo ""
echo "📄 Archivo template: dist/mexico.html"
echo "🎯 Archivo final: dist/mexico-final.html (después de pegar HTML)"
echo ""
